parameters:
  rust: stable
  allow_fail: false
  setup: []

jobs:
- job: ${{ parameters.name }}
  ${{ if eq(parameters.rust, 'stable') }}:
    displayName: cargo clippy
  ${{ if ne(parameters.rust, 'stable') }}:
    displayName: cargo +${{ parameters.rust }} clippy
  continueOnError: ${{ parameters.allow_fail }}
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: _setup.yml
      parameters:
        rust: ${{ parameters.rust }}
        setup: ${{ parameters.setup }}
        components:
          - clippy
    - script: cargo clippy --all
      displayName: Run clippy
