parameters:
  rust: stable

jobs:
- job: ${{ parameters.name }}
  ${{ if eq(parameters.rust, 'stable') }}:
    displayName: cargo check
  ${{ if ne(parameters.rust, 'stable') }}:
    displayName: cargo +${{ parameters.rust }} check
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install-rust.yml
    parameters:
      rust: ${{ parameters.rust }}
  - script: cargo check --all --bins --examples --tests
    displayName: Check compilation w/ default features
  - script: cargo check --all --bins --examples --tests --no-default-features
    displayName: Check compilation w/ no features
  - script: cargo check --all --bins --examples --tests --all-features
    displayName: Check compilation w/ all features
  - bash: "[[ -e Cargo.lock ]] && echo '##vso[task.setvariable variable=is_locked]true' || echo '##vso[task.setvariable variable=is_locked]false'"
    displayName: Are dependencies locked?
  # we only check with --tests here since we don't care about the actual
  # compilation, just the dependencies + dev-dependencies
  - script: cargo check --all --locked --tests --all-features
    condition: and(succeeded(), eq(variables.is_locked, 'true'))
    displayName: Check that Cargo.lock is satisfiable

  - ${{ if parameters.benches }}:
    - script: cargo check --benches --all
      displayName: Check benchmarks
