parameters:
  rust: stable
  benches: false
  setup: []
  all_features: false

jobs:
- job: ${{ parameters.name }}
  ${{ if eq(parameters.rust, 'stable') }}:
    displayName: cargo check
  ${{ if ne(parameters.rust, 'stable') }}:
    displayName: cargo +${{ parameters.rust }} check
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: _setup.yml
    parameters:
      rust: ${{ parameters.rust }}
      setup: ${{ parameters.setup }}
  - bash: |
      if git cat-file -e HEAD:Cargo.lock; then
        echo 'Found Cargo.lock';
        echo '##vso[task.setvariable variable=is_locked]true';
      else
        echo 'Did not find Cargo.lock';
        echo '##vso[task.setvariable variable=is_locked]false';
      fi
    displayName: Are dependencies locked?
  - script: cargo check --locked
    condition: and(succeeded(), eq(variables.is_locked, 'true'))
    displayName: Check that Cargo.lock is satisfiable
  - script: cargo check --workspace --bins --examples --tests
    displayName: Check compilation w/ default features
  - ${{ if eq('true', parameters.all_features) }}:
    - script: cargo check --workspace --bins --examples --tests --all-features
      displayName: Check compilation w/ all features

  - ${{ if ne('false', parameters.benches) }}:
    - script: cargo check --benches --workspace
      displayName: Check benchmarks
