parameters:
  envs: {}
  setup: []

jobs:
 - job: tarpaulin
   displayName: tarpaulin
   pool:
     vmImage: ubuntu-16.04
   container:
     image: xd009642/tarpaulin:latest
     options: --security-opt seccomp=unconfined
   steps:
     # workaround for https://github.com/MicrosoftDocs/vsts-docs/issues/4841
     # we sadly can't do this in a separate job, because:
     # https://developercommunity.visualstudio.com/content/problem/642219/setting-output-variable-when-multiple-stages-share.html
     # if we _could_, then we could set a condition on this whole job
     # which would let us avoid pulling down and spinning up the container
     # one day we may even be able to use this trick to skip the coverage stage
     # but we'll need https://github.com/MicrosoftDocs/vsts-docs/issues/4466
     # note that we intentionally do not leak the secret itself
     - script: "if [[ -n $CHECK ]] && [[ ! $CHECK == '$('* ]]; then echo '##vso[task.setvariable variable=has_secret]true'; else echo '##vso[task.setvariable variable=has_secret]false'; fi"
       name: secret_check
       displayName: Check for codecov token
       env:
         CHECK: ${{ parameters.codecov_token }}
     # Run any user-specific setup steps
     - ${{ parameters.setup }}
       condition: and(succeeded(), eq(variables.has_secret, 'true'))
     - script: cargo tarpaulin --out Xml
       displayName: Run tarpaulin
       condition: and(succeeded(), eq(variables.has_secret, 'true'))
       env:
         ${{ insert }}: ${{ parameters.envs }}
     - script: bash <(curl -s https://codecov.io/bash)
       displayName: Upload results to codecov
       condition: and(succeeded(), eq(variables.has_secret, 'true'))
       env:
         CODECOV_TOKEN: ${{ parameters.codecov_token }}
