parameters:
  setup: []
  canaries: true

jobs:
  - template: rustfmt.yml
    parameters:
      name: rustfmt
  - ${{ if eq(parameters.canaries, 'true') }}:
    - template: rustfmt.yml
      parameters:
        name: rustfmt_beta
        rust: beta
        allow_fail: true
  - template: cargo-clippy.yml
    parameters:
      name: clippy
      setup: ${{ parameters.setup }}
  - ${{ if eq(parameters.canaries, 'true') }}:
    - template: cargo-check.yml
      parameters:
        name: warning_free
        setup: ${{ parameters.setup }}
        err_on_warn: true
        allow_fail: true
  - ${{ if eq(parameters.canaries, 'true') }}:
    - template: cargo-clippy.yml
      parameters:
        name: clippy_beta
        setup: ${{ parameters.setup }}
        rust: beta
        allow_fail: true
