parameters:
  envs: {}

jobs:
 - template: test.yml
   parameters:
     name: cargo_test_stable
     cross: true # also test on Windows and macOS
     envs: ${{ parameters.envs }}
 - template: test.yml
   parameters:
     name: cargo_test_beta
     rust: beta
     envs: ${{ parameters.envs }}
 - template: test.yml
   parameters:
     name: cargo_test_nightly
     rust: nightly
     allow_fail: true
     envs: ${{ parameters.envs }}
