parameters:
  envs: {}
  setup: []
  test_ignored: false
  single_threaded: false
  nightly_feature: ''
  features: ''
  arguments: '--'

jobs:
 - template: test.yml
   parameters:
     name: cargo_test_stable
     cross: true # also test on Windows and macOS
     envs: ${{ parameters.envs }}
     setup: ${{ parameters.setup }}
     test_ignored: ${{ parameters.test_ignored }}
     single_threaded: ${{ parameters.single_threaded }}
     features: ${{ parameters.features }}
     arguments: ${{ parameters.arguments }}
 - template: test.yml
   parameters:
     name: cargo_test_beta
     rust: beta
     envs: ${{ parameters.envs }}
     setup: ${{ parameters.setup }}
     test_ignored: ${{ parameters.test_ignored }}
     single_threaded: ${{ parameters.single_threaded }}
     features: ${{ parameters.features }}
     arguments: ${{ parameters.arguments }}
 - template: test.yml
   parameters:
     name: cargo_test_nightly
     rust: nightly
     allow_fail: true
     envs: ${{ parameters.envs }}
     setup: ${{ parameters.setup }}
     test_ignored: ${{ parameters.test_ignored }}
     single_threaded: ${{ parameters.single_threaded }}
     features: "${{ parameters.features }},${{ parameters.nightly_feature }}"
     arguments: ${{ parameters.arguments }}
